name: Our CI

on:
  push:
  pull_request:
    branches:
      - main
      - other_branch
  workflow_dispatch:

# jobs:
#   hello:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "Hello World"
#       - name: Some name
#         run: echo "Hello again"

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: python -m pip install .{test}