name: Our CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - other_branch
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4 # actions/checkout@v4 -> does checkout
                                  # can also be done by specifying branch name, not recommended
                                  # In this case, it will checkout the version we're pushing/pulling
      - name: Set up python
        uses: actions/setup-python@v4 # To set up python when action is triggered
        with:
          python-version: "3.11" # You need to specify the version when using this
      - name: Install package
        run: python -m pip install .[test]
      - name: Run tests
        run: python -m pytest -v
  say_hello:
		steps:
			- run: echo "Hello there!"